### PR TITLE
Match the specification

### PR DESCRIPTION
**Pull request by acagastya**
I have:
1. Specified `ava` version in `package.json`'s `devDependency` to avoid crashing of `test.js`.
2. Updated `test.js` to work with `ava@3.2.0`.
3. Updated `isNaN` implementation to match as specified by [ECMA262](https://tc39.es/ecma262/#sec-number.isnan) specification.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Thanks, but don't change the code style.

**Comment by acagastya** [comment]
@sindresorhus  do you mean, one should skip checking the `typeof` the variable?

If that is so, I think it may not be a good idea.  ECMA262 specifies the procedure, and it is possible, in future a new feature is added which requires the function to adhere to the procedure they mentioned.  That would break the idea of ponyfill at the first place.

**Comment by sindresorhus** [comment]
No, I'm talking the quote and other *style* changes.

**Comment by acagastya** [comment]
Ah, I should have disabled Prettier for this file.

**Comment by acagastya** [comment]
Updated.

**Pull request merged**
